/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/1987_buick_grand_national_regal_gnx.glb --transform 
Files: public/1987_buick_grand_national_regal_gnx.glb [53.29MB] > /Users/hhe/Downloads/1f038745-edbd-4740-b87b-95d98b2a931c/1987_buick_grand_national_regal_gnx-transformed.glb [2.74MB] (95%)
Author: snafuj (https://sketchfab.com/snafuj)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1987-buick-grand-national-regal-gnx-4572494cd9cd432e8da50efb5c7a47c9
Title: 1987 Buick Grand National Regal GNX
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/1987_buick_grand_national_regal_gnx-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Body} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Emission_Red} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Fake_inside} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Lights} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Undercarriage} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Windows} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.White_Emission_Lamp} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Wheel} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/1987_buick_grand_national_regal_gnx-transformed.glb')
